name: Code Quality

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install deps (prod + dev linters)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt ruff

    - name: Check with Ruff
      run: |
        # Run Ruff linting in check mode (don't auto-fix)
        ruff check .

    - name: Check formatting with Ruff
      run: |
        # Verify code format
        ruff format --check .
