name: Run Tests

on:
  pull_request:
    branches:
      - "**"   # run on all PRs

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry && poetry install
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: |
          pytest -q --disable-warnings \
            --cov=app --cov-report=term-missing \
            --maxfail=1
